project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "slides/slides.qmd"

website:
  title: "Git and GitHub"
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - href: exercises.qmd
        text: Exercises
      - href: slides/slides.html
        text: Slides
    right:
      - text: "NIHR Maudsley BRC"
        href: "https://www.maudsleybrc.nihr.ac.uk"
  page-footer:
    left: "NIHR Maudsley BRC · King's College London · April 2026"

format:
  html:
    theme: [cosmo, website.scss]
    toc: true
    code-copy: true
